guybedford/chomp

- .gitignore
- install.sh
- src/engines/mod.rs
- src/task.rs
- src/templates.toml
- templates/babel.toml
- templates/jspm.toml
- templates/npm.toml
- templates/svelte.toml
- templates/swc.toml
- test/chompfile.toml
This PR updates the templates based on current usability feedback.
It adds an `autoInstall = true` argument to all templates that do npm installs, where when that argument is not explicitly set for the template, there will instead be an error thrown that a package is missing and needs to be installed like:
```
Chomp: Some packages are missing. Please run npm install @babel/core @babel/cli
```
In addition the Babel and SWC templates now use configuration files by default with an argument to disable them.
Template updates:
NPM
* Adds a new `npm:verify` template that is exactly the same as the `npm:install` template but instead of installing, throws and error stopping all subsequent operations with a failure and informs the user with the message `Chomp: Some packages are missing. Please run …
> Template features + autoinstalls

- Cargo.lock
- Cargo.toml
- README.md
- src/chompfile.rs
- src/js.rs
- src/main.rs
- src/task.rs
- src/templates.toml
- templates/babel.toml
- templates/jspm.toml
- templates/npm.toml
- templates/prettier.toml
- templates/svelte.toml
- templates/swc.toml
- test/chompfile.toml
This PR implements a number of renamings and adjustments to the template system, fixing a number of issues in the process.
* As a rule, all properties in the `chompfile.toml` are now `kebab-case` per convention.
* `[task.args]` for setting template options has been renamed to `[task.template-opts]` to make it clearer what this is doing.
* A new `[default-template-opts.template-name]` top-level setting is now provided for setting default options by template. Resolves https://github.com/guybedford/chomp/issues/27.
* `autoInstall` is now `auto-install`, and `PKG_MANAGER` is no longer an environment variable but rather a template option `pkg-manager`
* The `jspm:generate` template is renamed to just `jspm`.
This PR also adopts a manual chaining of template options within the template …
> feat: template options refinements

- README.md
- src/chompfile.rs
- src/task.rs
- src/templates.toml
- templates/babel.toml
- templates/jspm.toml
- templates/npm.toml
- templates/prettier.toml
- templates/svelte.toml
- templates/swc.toml
- test/chompfile.toml
This renames the `template-opts` option to just `options`, per discussion in https://github.com/guybedford/chomp/issues/32.
It might make it simpler to just think of this as global default options and task options. The fact that they are applying to and keyed by templates is perhaps less important to highlight than ensuring users just appreciate template tasks take options.
Before:
```toml
[default-template-opts.npm]
pkg-manager = 'pnpm'
[[task]]
template = 'svelte'
[task.template-opts]
auto-install = true
```
After:
```toml
[default-options.npm]
package-manager = 'pnpm'
[[task]]
template = 'svelte'
[task.options]
auto-install = true
```
> Rename template-opts -> options

- src/chompfile.rs
- src/task.rs
- src/templates.toml
- templates/babel.toml
- templates/jspm.toml
- templates/npm.toml
- templates/prettier.toml
- templates/svelte.toml
- templates/swc.toml
- test/chompfile.toml
This reverts the change of `template-opts` to `options` to be back to `template-options`, as well as some bug fixes with direct target builds.
The global is now `template-options` as well without the `default`.
BEFORE:
```toml
[default-options.npm]
package-manager = 'pnpm'
[[task]]
template = 'swc'
[task.options]
auto-install = true
[task.options.config]
"jsc.parser.jsx" = true
```
AFTER:
```toml
[template-options.npm]
package-manager = 'pnpm'
[[task]]
template = 'swc'
[task.template-options]
auto-install = true
[task.template-options.config]
"jsc.parser.jsx" = true
```
> options -> template-options, bug fixes

- Cargo.lock
- Cargo.toml
- README.md
- docs/cli.md
- docs/task.md
- src/main.rs
This PR provides two new features:
1. `chomp --init` / `chomp -i` will create `chompfile.toml` if it does not already exist.
2. `chomp --import-scripts` / `chomp -I` will import package.json "scripts" from an npm workflow prepopulating these into the associated Chomp tasks so that `npm run build` can be migrated to `chomp build` as simply as `chomp --import-scripts build`.
Associated documentation is provided.
> Feat: `chomp --init` and `chomp --import-scripts`

- Cargo.lock
- docs/task.md
- src/chompfile.rs
- src/engines/cmd.rs
- src/engines/mod.rs
- src/main.rs
- src/task.rs
- test/chompfile.toml
Runtime environment variable usage via `$VAR` works well in most cases, but has limitations when it comes to for example executing a command at a path, where `$VAR/bin/app` isn't supported in Powershell so there's no cross-platform way to do this.
This adds `${{VAR}}` static replacements, and uses these for environment variable replacements in environment variables themselves as well as for the `run` script of Shell tasks only.
A new option `env-replacements = false` can be used to disable this per-task in the rare case of conflict.
Any `${{..}}` which cannot be resolved will be replaced with the empty string, so in theory we could extend the syntax to basic execution syntax in future, but for now it's just direct variable replacements only. The use of `$VAR` replacements in environment …
> feat: static environment variable replacements

- docs/task.md
- src/task.rs
- test/chompfile.toml
This updates the deps expansion into the `DEPS` environment variable for a task to always include the exact list of file dependencies with the following rules:
* If the dependency is a task by name, the deps will be expanded to include the file targets of that task
* If the dependency is a glob, the glob will be expanded into file paths
* If the dependency is an interpolation task, all interpolated targets will be expanded
If a task defines multiple target paths, and another task depends on only one of those target paths, DEPS will be expanded to include the full list of targets defined by the first task. This may be too much, but it is because the task graph does not distinguish between depending on a job and depending only on some files of a job. If it turns out to be an issue, this can …
> feat: comprehensive deps expansion

- docs/cli.md
- src/main.rs
- src/task.rs
- test/chompfile.toml
This adds a new flag `chomp -r` or `chomp --rerun` to just rerun the top-level task that is requested.
When developing tasks, this is useful to avoid a full `--force` build which will invalidate everything and instead just rebuild the task that is being specified by the user while keeping the rest of the cache.
> feat: chomp --rerun as --force alternative

- src/task.rs
Currently `chomp --force` will invalidate all tasks, including init tasks which use the `invalidation = 'not-found'` pattern, which can have unwanted results.
This makes force skip `invalidation = 'not-found'` "init tasks".
> feat: chomp --force should not invalidate not-found tasks

- src/main.rs
There was a bug with `chomp --init`, which this resolves.
> fix: chomp --init

- docs/task.md
- src/task.rs
This updates the `TARGETS` environment variable to be `:` separated like `DEPS` instead of comma separated.
> fix: match targets and deps separators

- src/task.rs
- test/chompfile.toml
This ordering fix makes it easier for global default environment variables to be replaced into environment variables on tasks.
> Fix: Env override ordering

- src/chompfile.rs
- src/engines/mod.rs
- src/main.rs
- src/task.rs
This adds a new `display = 'dot'` task output, useful for tests, for example with:
```toml
[[task]]
name = 'test:#'
serial = true
deps = ['test/#.test.js']
display = 'dot'
stdio = 'stderr-only'
run = 'node $DEP'
```
This also fixes the `-j` flag which was off-by-one, and updates the extensions.
> feat: dot reporter, fixes

- docs/extensions.md
- src/extensions.rs
- src/main.rs
This includes an update to the environment variable handling in the extensions environment to ensure they get the environment variables defined by the Chompfile `[env]` and `[default-env]`.
This can then replace the package manager customization mechanism, which the latest extensions update implements.
> feat: extensions update to environment handling

- install.sh
- src/engines/node.rs
- src/main.rs
This fixes a posix execution bug where Node.js tasks would execute before their temporary files were ready for execution.
> fix: posix execution bug

- src/engines/mod.rs
- src/extensions.rs
- src/http_client.rs
- src/main.rs
- src/task.rs
This adds support for ejection of static `Chomp.addTask` declarations in extensions, specifically in the npm workflow to eject the `npm:install` task.
Also resolves https://github.com/guybedford/chomp/issues/75.
> feat: permit extension task ejection

- src/main.rs
This fixes a bug where default environment would incorrectly override in the extension environment.
> fix: default env overrides

- docs/task.md
- src/chompfile.rs
- src/engines/cmd.rs
- src/engines/deno.rs
- src/engines/mod.rs
- src/engines/node.rs
- src/extensions.rs
- src/main.rs
- src/task.rs
Resolves https://github.com/guybedford/chomp/issues/73 in providing a per-task and global task shell logging.
This also refactors the `Task` implementation to reference the direct Chompfile tasks, cutting down on duplicated logic and data.
> feat: echo implementation

- src/engines/node.rs
The Node.js engine was no longer working on the latest Node.js since the data: URL loader doesn't have access to the `import 'fs'` anymore for security in the HTTPs imports PR.
This updates the loader to work without needing any extra files present, which also usefully makes the `echo = true` output for Node.js tasks, while percent encoded, the actual correct execution which can be copied and pasted to run the task locally if desired, which seems a useful property.
> fix: Node.js engine on latest

- src/main.rs
- test/chompfile.toml
Resolves #99 supporting `chomp -c ./subdir` to mean `chomp -c ./subdir/chompfile.toml`.
> feat: default to chompfile.toml for directories

- src/main.rs
- test/chompfile.toml
This fixes support of `--import-scripts` with an existing chompfile as well as improving interaction between other modifier flags. Resolves #97.
> fix: --import-scripts with existing chompfile, interactions

- README.md
- docs/cli.md
- docs/task.md
- src/main.rs
- src/task.rs
- test/chompfile.toml
Adds support for `##` interpolates as corresponding to `**/*` globs, while `#` interpolates are only `*` globs.
Resolves https://github.com/guybedford/chomp/issues/100.
> feat: double interpolates

- src/chompfile.rs
- src/engines/cmd.rs
- src/task.rs
- test/chompfile.toml
This ensures for multi-step scripts in powershell or sh will stop on the first error strictly instead of proceeding, and ensuring the exit code is an error.
Resolves https://github.com/guybedford/chomp/issues/98.
> fix: stop commands on error

- src/engines/cmd.rs
Commands in a linux environment were being executed via `sh`, rather than via `bash`. I found this because I was trying to `source env.sh`, which only works in the context of bash
> Update cmd.rs execution context from "sh" to "bash"

- src/main.rs
This fixes a bug from the auto-directory handling for `chomp -c ./dir` stopping `chomp --init -c x.toml` style workflows from working.
> fix: auto chompfile.toml for directories

- src/main.rs
Fixes a bug where `chomp --list` would run the default task.
> fix: --list should not run default task

- src/main.rs
- src/task.rs
This fixes a number of interpolation edge cases:
* When the path matching an interpolation was shorter than the interpolation pattern (ie when using `##` with a single character file), there was an integer overflow which is now fixed.
* When the target of an interpolation was used to drive another interpolation in turn, that further interpolation wouldn't trigger until the second run of the build. This fixes that by handling the interpolation expansion as itself driving further interpolations as necessary. Ideally this should fully integrate into all globbed dependencies, and a comment noting this has been added.
* When the target of an interpolation also matches the dependency pattern of that same interpolation, this results in recursion. To fix this, interpolation dependencies which in …
> fix: interpolation edge cases

- src/chompfile.rs
- src/extensions.rs
- src/task.rs
Adds a new `watch-invalidation` configuration option which allows customizing how invalidations for long-running tasks should work.
The default is the existing behaviour of terminating and re-running the currently running task, with a new option, `watch-invalidation: 'skip-running'` which skips termination and re-execution if the task is already running.
> feat: watch-invalidation option

- docs/task.md
Changed `default_task` to `default-task`, since the latter works with chomp v0.2.6
> Typo in readme

- Cargo.lock
- Cargo.toml
- src/main.rs
Updates all dependencies for the next release.
@Aslemammad the tests here are actually failing on Windows due to the relative path function outputting `path\\to\\file` for the TARGET instead of `path/to/file`. Perhaps we should normalize on forward slashes? Or at least we should change the tests.
Another thing I noticed with the output is that the task log includes the full path now as well:
```
√ :build [49.5350901s]
🞂 :test
√ :test:clean [962.1308ms]
🞂 :test7
🞂 C:\Users\Guy\Projects\chomp\test\output
√ :test2 [55.725ms]]
√ :test1 [55.8852ms]
```
Perhaps we should update this to also use the same relative function again:
```
√ :build [49.5350901s]
🞂 :test
√ :test:clean [962.1308ms]
🞂 :test7
🞂 test/output
√ :test2 [55.725ms]]
√ :test1 [55.8852ms]
```
Where backtracking is only added as it …
> deps: update dependencies

- docs/chompfile.md
- docs/task.md
- src/main.rs
This makes the `default-task` always `"build"`. I've found having `chomp` just work in all Chomp projects to get things running is a pretty good pattern to follow usually.
> feat: set default task to build

- Cargo.lock
- src/chompfile.rs
- src/main.rs
- src/task.rs
This fixes Windows path normalizations with the new absolute pathing by using `/` over `\` in keys.
Resolves https://github.com/guybedford/chomp/issues/150.
> fix: windows path normalizations

- src/engines/mod.rs
Fixes the build start character to be compatible on macs.
> fix: execution triangle mac support

- Cargo.lock
- src/main.rs
This resolves https://github.com/guybedford/chomp/issues/158, and also updates the dependencies.
> fix: chomp without chompfile, upgrade deps

- docs/task.md
- src/chompfile.rs
- src/engines/cmd.rs
- src/engines/deno.rs
- src/engines/mod.rs
- src/engines/node.rs
- src/main.rs
- src/task.rs
When setting the `cwd` on a specific task, this was causing the `node_modules/.bin` automatic path inclusion to be relative to that task-specific cwd. Instead we use the Chompfile-level cwd here so that we use a consistent path lookup across all tasks and task-specific cwds do not affect the script pathing.
There could be an argument for mono repo patterns where commands should first be looked up in node_modules folders in sub-packages. I think that this should rather be tackled as any workspace work though in treating the path fallback as being from the workspace to the project here as part of the workspace support.
> fix: path lookups chompfile-cwd relative

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- src/engines/cmd.rs
This should resolve the issue on Linux where dynamic linking with openssl sometimes does not work, depending on the system.
Fixes #168
> Add rustls to build, removing dependency on openssl

- Cargo.lock
- Cargo.toml
This is to fix the following error running `cargo install chompbuild` with latest rustc version `1.77.1`:
```
error[E0080]: evaluation of constant value failed
--> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.51.0/src/isolate.rs:1273:3
|
1273 |   assert!(size_of::<TypeId>() == size_of::<u64>());
|   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'assertion failed: size_of::<TypeId>() == size_of::<u64>()', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/v8-0.51.0/src/isolate.rs:1273:3
|
= note: this error originates in the macro `assert` (in Nightly builds, run with -Z macro-backtrace for more info)
For more information about this error, try `rustc --explain E0080`.
error: could not compile `v8` (lib) due to 1 …
```
> Update `v8` and `serde_v8` to latest
